//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tableau.com/api", IsNullable=false)]
public partial class tsRequest {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("connection", typeof(connectionType))]
    [System.Xml.Serialization.XmlElementAttribute("credentials", typeof(tableauCredentialsType))]
    [System.Xml.Serialization.XmlElementAttribute("datasource", typeof(dataSourceType))]
    [System.Xml.Serialization.XmlElementAttribute("favorite", typeof(favoriteType))]
    [System.Xml.Serialization.XmlElementAttribute("group", typeof(groupType))]
    [System.Xml.Serialization.XmlElementAttribute("permissions", typeof(permissionsType))]
    [System.Xml.Serialization.XmlElementAttribute("project", typeof(projectType))]
    [System.Xml.Serialization.XmlElementAttribute("site", typeof(siteType))]
    [System.Xml.Serialization.XmlElementAttribute("tags", typeof(tagListType))]
    [System.Xml.Serialization.XmlElementAttribute("user", typeof(userType))]
    [System.Xml.Serialization.XmlElementAttribute("workbook", typeof(workbookType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class connectionType {
    
    private string idField;
    
    private string typeField;
    
    private string serverAddressField;
    
    private string serverPortField;
    
    private string userNameField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serverAddress {
        get {
            return this.serverAddressField;
        }
        set {
            this.serverAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string serverPort {
        get {
            return this.serverPortField;
        }
        set {
            this.serverPortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string userName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class statusNoteType {
    
    private statusNoteTypeType typeField;
    
    private string valueField;
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public statusNoteTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum statusNoteTypeType {
    
    /// <remarks/>
    CountOfUsersAddedToGroup,
    
    /// <remarks/>
    CountOfUsersAddedToSite,
    
    /// <remarks/>
    CountOfUsersWithInsufficientLicenses,
    
    /// <remarks/>
    CountOfUsersInActiveDirectoryGroup,
    
    /// <remarks/>
    CountOfUsersProcessed,
    
    /// <remarks/>
    CountOfUsersSkipped,
    
    /// <remarks/>
    CountOfUsersInformationUpdated,
    
    /// <remarks/>
    CountOfUsersSiteRoleUpdated,
    
    /// <remarks/>
    CountOfUsersRemovedFromGroup,
    
    /// <remarks/>
    CountOfUsersUnlicensed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class jobType {
    
    private statusNoteType[] statusNotesField;
    
    private string idField;
    
    private jobTypeMode modeField;
    
    private bool modeFieldSpecified;
    
    private jobTypeType typeField;
    
    private bool typeFieldSpecified;
    
    private string progressField;
    
    private System.DateTime createdAtField;
    
    private bool createdAtFieldSpecified;
    
    private System.DateTime updatedAtField;
    
    private bool updatedAtFieldSpecified;
    
    private System.DateTime completedAtField;
    
    private bool completedAtFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("statusNote", IsNullable=false)]
    public statusNoteType[] statusNotes {
        get {
            return this.statusNotesField;
        }
        set {
            this.statusNotesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public jobTypeMode mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool modeSpecified {
        get {
            return this.modeFieldSpecified;
        }
        set {
            this.modeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public jobTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string progress {
        get {
            return this.progressField;
        }
        set {
            this.progressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime createdAt {
        get {
            return this.createdAtField;
        }
        set {
            this.createdAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createdAtSpecified {
        get {
            return this.createdAtFieldSpecified;
        }
        set {
            this.createdAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime updatedAt {
        get {
            return this.updatedAtField;
        }
        set {
            this.updatedAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updatedAtSpecified {
        get {
            return this.updatedAtFieldSpecified;
        }
        set {
            this.updatedAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime completedAt {
        get {
            return this.completedAtField;
        }
        set {
            this.completedAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool completedAtSpecified {
        get {
            return this.completedAtFieldSpecified;
        }
        set {
            this.completedAtFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum jobTypeMode {
    
    /// <remarks/>
    Asynchronous,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum jobTypeType {
    
    /// <remarks/>
    GroupSync,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class fileUploadType {
    
    private string uploadSessionIdField;
    
    private string fileSizeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uploadSessionId {
        get {
            return this.uploadSessionIdField;
        }
        set {
            this.uploadSessionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string fileSize {
        get {
            return this.fileSizeField;
        }
        set {
            this.fileSizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class favoriteListType {
    
    private favoriteType[] favoriteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("favorite")]
    public favoriteType[] favorite {
        get {
            return this.favoriteField;
        }
        set {
            this.favoriteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class favoriteType {
    
    private object itemField;
    
    private string labelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("view", typeof(viewType))]
    [System.Xml.Serialization.XmlElementAttribute("workbook", typeof(workbookType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class viewType {
    
    private workbookType workbookField;
    
    private userType ownerField;
    
    private viewTypeUsage usageField;
    
    private string idField;
    
    private string nameField;
    
    private string contentUrlField;
    
    /// <remarks/>
    public workbookType workbook {
        get {
            return this.workbookField;
        }
        set {
            this.workbookField = value;
        }
    }
    
    /// <remarks/>
    public userType owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    public viewTypeUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contentUrl {
        get {
            return this.contentUrlField;
        }
        set {
            this.contentUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class workbookType {
    
    private connectionCredentialsType connectionCredentialsField;
    
    private siteType siteField;
    
    private projectType projectField;
    
    private userType ownerField;
    
    private tagType[] tagsField;
    
    private viewType[] viewsField;
    
    private string idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private string contentUrlField;
    
    private bool showTabsField;
    
    private bool showTabsFieldSpecified;
    
    private string sizeField;
    
    private System.DateTime createdAtField;
    
    private bool createdAtFieldSpecified;
    
    private System.DateTime updatedAtField;
    
    private bool updatedAtFieldSpecified;
    
    /// <remarks/>
    public connectionCredentialsType connectionCredentials {
        get {
            return this.connectionCredentialsField;
        }
        set {
            this.connectionCredentialsField = value;
        }
    }
    
    /// <remarks/>
    public siteType site {
        get {
            return this.siteField;
        }
        set {
            this.siteField = value;
        }
    }
    
    /// <remarks/>
    public projectType project {
        get {
            return this.projectField;
        }
        set {
            this.projectField = value;
        }
    }
    
    /// <remarks/>
    public userType owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("tag", IsNullable=false)]
    public tagType[] tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("view", IsNullable=false)]
    public viewType[] views {
        get {
            return this.viewsField;
        }
        set {
            this.viewsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contentUrl {
        get {
            return this.contentUrlField;
        }
        set {
            this.contentUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool showTabs {
        get {
            return this.showTabsField;
        }
        set {
            this.showTabsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool showTabsSpecified {
        get {
            return this.showTabsFieldSpecified;
        }
        set {
            this.showTabsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime createdAt {
        get {
            return this.createdAtField;
        }
        set {
            this.createdAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createdAtSpecified {
        get {
            return this.createdAtFieldSpecified;
        }
        set {
            this.createdAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime updatedAt {
        get {
            return this.updatedAtField;
        }
        set {
            this.updatedAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updatedAtSpecified {
        get {
            return this.updatedAtFieldSpecified;
        }
        set {
            this.updatedAtFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class connectionCredentialsType {
    
    private string nameField;
    
    private string passwordField;
    
    private bool embedField;
    
    private bool embedFieldSpecified;
    
    private bool oAuthField;
    
    private bool oAuthFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool embed {
        get {
            return this.embedField;
        }
        set {
            this.embedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool embedSpecified {
        get {
            return this.embedFieldSpecified;
        }
        set {
            this.embedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool oAuth {
        get {
            return this.oAuthField;
        }
        set {
            this.oAuthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool oAuthSpecified {
        get {
            return this.oAuthFieldSpecified;
        }
        set {
            this.oAuthFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class siteType {
    
    private siteTypeUsage usageField;
    
    private string idField;
    
    private string nameField;
    
    private string contentUrlField;
    
    private siteTypeAdminMode adminModeField;
    
    private bool adminModeFieldSpecified;
    
    private string userQuotaField;
    
    private string storageQuotaField;
    
    private bool disableSubscriptionsField;
    
    private bool disableSubscriptionsFieldSpecified;
    
    private stateType stateField;
    
    private bool stateFieldSpecified;
    
    /// <remarks/>
    public siteTypeUsage usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contentUrl {
        get {
            return this.contentUrlField;
        }
        set {
            this.contentUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public siteTypeAdminMode adminMode {
        get {
            return this.adminModeField;
        }
        set {
            this.adminModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool adminModeSpecified {
        get {
            return this.adminModeFieldSpecified;
        }
        set {
            this.adminModeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string userQuota {
        get {
            return this.userQuotaField;
        }
        set {
            this.userQuotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string storageQuota {
        get {
            return this.storageQuotaField;
        }
        set {
            this.storageQuotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool disableSubscriptions {
        get {
            return this.disableSubscriptionsField;
        }
        set {
            this.disableSubscriptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool disableSubscriptionsSpecified {
        get {
            return this.disableSubscriptionsFieldSpecified;
        }
        set {
            this.disableSubscriptionsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public stateType state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stateSpecified {
        get {
            return this.stateFieldSpecified;
        }
        set {
            this.stateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public partial class siteTypeUsage {
    
    private string numUsersField;
    
    private string storageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string numUsers {
        get {
            return this.numUsersField;
        }
        set {
            this.numUsersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string storage {
        get {
            return this.storageField;
        }
        set {
            this.storageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum siteTypeAdminMode {
    
    /// <remarks/>
    ContentOnly,
    
    /// <remarks/>
    ContentAndUsers,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public enum stateType {
    
    /// <remarks/>
    Active,
    
    /// <remarks/>
    Suspended,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class projectType {
    
    private userType ownerField;
    
    private string idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private projectTypeContentPermissions contentPermissionsField;
    
    private bool contentPermissionsFieldSpecified;
    
    /// <remarks/>
    public userType owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public projectTypeContentPermissions contentPermissions {
        get {
            return this.contentPermissionsField;
        }
        set {
            this.contentPermissionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool contentPermissionsSpecified {
        get {
            return this.contentPermissionsFieldSpecified;
        }
        set {
            this.contentPermissionsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class userType {
    
    private domainDirectiveType domainField;
    
    private string idField;
    
    private string nameField;
    
    private string fullNameField;
    
    private string emailField;
    
    private string passwordField;
    
    private siteRoleType siteRoleField;
    
    private bool siteRoleFieldSpecified;
    
    private siteUserAuthSettingType authSettingField;
    
    private bool authSettingFieldSpecified;
    
    private System.DateTime lastLoginField;
    
    private bool lastLoginFieldSpecified;
    
    private string externalAuthUserIdField;
    
    /// <remarks/>
    public domainDirectiveType domain {
        get {
            return this.domainField;
        }
        set {
            this.domainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public siteRoleType siteRole {
        get {
            return this.siteRoleField;
        }
        set {
            this.siteRoleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool siteRoleSpecified {
        get {
            return this.siteRoleFieldSpecified;
        }
        set {
            this.siteRoleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public siteUserAuthSettingType authSetting {
        get {
            return this.authSettingField;
        }
        set {
            this.authSettingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool authSettingSpecified {
        get {
            return this.authSettingFieldSpecified;
        }
        set {
            this.authSettingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime lastLogin {
        get {
            return this.lastLoginField;
        }
        set {
            this.lastLoginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastLoginSpecified {
        get {
            return this.lastLoginFieldSpecified;
        }
        set {
            this.lastLoginFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string externalAuthUserId {
        get {
            return this.externalAuthUserIdField;
        }
        set {
            this.externalAuthUserIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class domainDirectiveType {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public enum siteRoleType {
    
    /// <remarks/>
    Guest,
    
    /// <remarks/>
    Interactor,
    
    /// <remarks/>
    Publisher,
    
    /// <remarks/>
    ServerAdministrator,
    
    /// <remarks/>
    SiteAdministrator,
    
    /// <remarks/>
    Unlicensed,
    
    /// <remarks/>
    UnlicensedWithPublish,
    
    /// <remarks/>
    Viewer,
    
    /// <remarks/>
    ViewerWithPublish,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public enum siteUserAuthSettingType {
    
    /// <remarks/>
    ServerDefault,
    
    /// <remarks/>
    SAML,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum projectTypeContentPermissions {
    
    /// <remarks/>
    LockedToProject,
    
    /// <remarks/>
    ManagedByOwner,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class tagType {
    
    private string labelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public partial class viewTypeUsage {
    
    private string totalViewCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string totalViewCount {
        get {
            return this.totalViewCountField;
        }
        set {
            this.totalViewCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class errorType {
    
    private string summaryField;
    
    private string detailField;
    
    private string codeField;
    
    /// <remarks/>
    public string summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    public string detail {
        get {
            return this.detailField;
        }
        set {
            this.detailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class connectionListType {
    
    private connectionType[] connectionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("connection")]
    public connectionType[] connection {
        get {
            return this.connectionField;
        }
        set {
            this.connectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class workbookListType {
    
    private workbookType[] workbookField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("workbook")]
    public workbookType[] workbook {
        get {
            return this.workbookField;
        }
        set {
            this.workbookField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class userListType {
    
    private userType[] userField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("user")]
    public userType[] user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class siteListType {
    
    private siteType[] siteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("site")]
    public siteType[] site {
        get {
            return this.siteField;
        }
        set {
            this.siteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class scheduleListType {
    
    private scheduleType[] scheduleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("schedule")]
    public scheduleType[] schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class scheduleType {
    
    private string idField;
    
    private string nameField;
    
    private stateType stateField;
    
    private bool stateFieldSpecified;
    
    private string priorityField;
    
    private System.DateTime createdAtField;
    
    private bool createdAtFieldSpecified;
    
    private System.DateTime updatedAtField;
    
    private bool updatedAtFieldSpecified;
    
    private scheduleTypeType typeField;
    
    private bool typeFieldSpecified;
    
    private scheduleTypeFrequency frequencyField;
    
    private bool frequencyFieldSpecified;
    
    private System.DateTime nextRunAtField;
    
    private bool nextRunAtFieldSpecified;
    
    private System.DateTime endScheduleAtField;
    
    private bool endScheduleAtFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public stateType state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stateSpecified {
        get {
            return this.stateFieldSpecified;
        }
        set {
            this.stateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime createdAt {
        get {
            return this.createdAtField;
        }
        set {
            this.createdAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createdAtSpecified {
        get {
            return this.createdAtFieldSpecified;
        }
        set {
            this.createdAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime updatedAt {
        get {
            return this.updatedAtField;
        }
        set {
            this.updatedAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updatedAtSpecified {
        get {
            return this.updatedAtFieldSpecified;
        }
        set {
            this.updatedAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public scheduleTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public scheduleTypeFrequency frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool frequencySpecified {
        get {
            return this.frequencyFieldSpecified;
        }
        set {
            this.frequencyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime nextRunAt {
        get {
            return this.nextRunAtField;
        }
        set {
            this.nextRunAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nextRunAtSpecified {
        get {
            return this.nextRunAtFieldSpecified;
        }
        set {
            this.nextRunAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime endScheduleAt {
        get {
            return this.endScheduleAtField;
        }
        set {
            this.endScheduleAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endScheduleAtSpecified {
        get {
            return this.endScheduleAtFieldSpecified;
        }
        set {
            this.endScheduleAtFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum scheduleTypeType {
    
    /// <remarks/>
    Extract,
    
    /// <remarks/>
    Subscription,
    
    /// <remarks/>
    ActiveDirectorySync,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum scheduleTypeFrequency {
    
    /// <remarks/>
    Hourly,
    
    /// <remarks/>
    Daily,
    
    /// <remarks/>
    Weekly,
    
    /// <remarks/>
    Monthly,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class projectListType {
    
    private projectType[] projectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("project")]
    public projectType[] project {
        get {
            return this.projectField;
        }
        set {
            this.projectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class groupListType {
    
    private groupType[] groupField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group")]
    public groupType[] group {
        get {
            return this.groupField;
        }
        set {
            this.groupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class groupType {
    
    private domainDirectiveType domainField;
    
    private importDirectiveType importField;
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    public domainDirectiveType domain {
        get {
            return this.domainField;
        }
        set {
            this.domainField = value;
        }
    }
    
    /// <remarks/>
    public importDirectiveType import {
        get {
            return this.importField;
        }
        set {
            this.importField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class importDirectiveType {
    
    private importSourceType sourceField;
    
    private string domainNameField;
    
    private siteRoleType siteRoleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public importSourceType source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string domainName {
        get {
            return this.domainNameField;
        }
        set {
            this.domainNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public siteRoleType siteRole {
        get {
            return this.siteRoleField;
        }
        set {
            this.siteRoleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public enum importSourceType {
    
    /// <remarks/>
    ActiveDirectory,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class extractListType {
    
    private extractType[] extractField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("extract")]
    public extractType[] extract {
        get {
            return this.extractField;
        }
        set {
            this.extractField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class extractType {
    
    private object itemField;
    
    private string idField;
    
    private string priorityField;
    
    private extractTypeType typeField;
    
    private bool typeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("datasource", typeof(dataSourceType))]
    [System.Xml.Serialization.XmlElementAttribute("workbook", typeof(workbookType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public extractTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool typeSpecified {
        get {
            return this.typeFieldSpecified;
        }
        set {
            this.typeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class dataSourceType {
    
    private connectionCredentialsType connectionCredentialsField;
    
    private siteType siteField;
    
    private projectType projectField;
    
    private userType ownerField;
    
    private tagType[] tagsField;
    
    private string idField;
    
    private string nameField;
    
    private string contentUrlField;
    
    private string descriptionField;
    
    private string typeField;
    
    private System.DateTime createdAtField;
    
    private bool createdAtFieldSpecified;
    
    private System.DateTime updatedAtField;
    
    private bool updatedAtFieldSpecified;
    
    /// <remarks/>
    public connectionCredentialsType connectionCredentials {
        get {
            return this.connectionCredentialsField;
        }
        set {
            this.connectionCredentialsField = value;
        }
    }
    
    /// <remarks/>
    public siteType site {
        get {
            return this.siteField;
        }
        set {
            this.siteField = value;
        }
    }
    
    /// <remarks/>
    public projectType project {
        get {
            return this.projectField;
        }
        set {
            this.projectField = value;
        }
    }
    
    /// <remarks/>
    public userType owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("tag", IsNullable=false)]
    public tagType[] tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contentUrl {
        get {
            return this.contentUrlField;
        }
        set {
            this.contentUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime createdAt {
        get {
            return this.createdAtField;
        }
        set {
            this.createdAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool createdAtSpecified {
        get {
            return this.createdAtFieldSpecified;
        }
        set {
            this.createdAtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime updatedAt {
        get {
            return this.updatedAtField;
        }
        set {
            this.updatedAtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updatedAtSpecified {
        get {
            return this.updatedAtFieldSpecified;
        }
        set {
            this.updatedAtFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum extractTypeType {
    
    /// <remarks/>
    IncrementalRefresh,
    
    /// <remarks/>
    FullRefresh,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class dataSourceListType {
    
    private dataSourceType[] datasourceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("datasource")]
    public dataSourceType[] datasource {
        get {
            return this.datasourceField;
        }
        set {
            this.datasourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class paginationType {
    
    private string pageNumberField;
    
    private string pageSizeField;
    
    private string totalAvailableField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string pageNumber {
        get {
            return this.pageNumberField;
        }
        set {
            this.pageNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string pageSize {
        get {
            return this.pageSizeField;
        }
        set {
            this.pageSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string totalAvailable {
        get {
            return this.totalAvailableField;
        }
        set {
            this.totalAvailableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class capabilityType {
    
    private capabilityTypeName nameField;
    
    private capabilityTypeMode modeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public capabilityTypeName name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public capabilityTypeMode mode {
        get {
            return this.modeField;
        }
        set {
            this.modeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum capabilityTypeName {
    
    /// <remarks/>
    AddComment,
    
    /// <remarks/>
    ChangeHierarchy,
    
    /// <remarks/>
    ChangePermissions,
    
    /// <remarks/>
    Connect,
    
    /// <remarks/>
    Delete,
    
    /// <remarks/>
    ExportData,
    
    /// <remarks/>
    ExportImage,
    
    /// <remarks/>
    ExportXml,
    
    /// <remarks/>
    Filter,
    
    /// <remarks/>
    ProjectLeader,
    
    /// <remarks/>
    Read,
    
    /// <remarks/>
    ShareView,
    
    /// <remarks/>
    ViewComments,
    
    /// <remarks/>
    ViewUnderlyingData,
    
    /// <remarks/>
    WebAuthoring,
    
    /// <remarks/>
    Write,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum capabilityTypeMode {
    
    /// <remarks/>
    Allow,
    
    /// <remarks/>
    Deny,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class granteeCapabilitiesType {
    
    private object itemField;
    
    private capabilityType[] capabilitiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("group", typeof(groupType))]
    [System.Xml.Serialization.XmlElementAttribute("user", typeof(userType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("capability", IsNullable=false)]
    public capabilityType[] capabilities {
        get {
            return this.capabilitiesField;
        }
        set {
            this.capabilitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class parentType {
    
    private string idField;
    
    private parentTypeType typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public parentTypeType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
public enum parentTypeType {
    
    /// <remarks/>
    Project,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class permissionsType {
    
    private parentType parentField;
    
    private object itemField;
    
    private granteeCapabilitiesType[] granteeCapabilitiesField;
    
    /// <remarks/>
    public parentType parent {
        get {
            return this.parentField;
        }
        set {
            this.parentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("datasource", typeof(dataSourceType))]
    [System.Xml.Serialization.XmlElementAttribute("project", typeof(projectType))]
    [System.Xml.Serialization.XmlElementAttribute("workbook", typeof(workbookType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("granteeCapabilities")]
    public granteeCapabilitiesType[] granteeCapabilities {
        get {
            return this.granteeCapabilitiesField;
        }
        set {
            this.granteeCapabilitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class viewListType {
    
    private viewType[] viewField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("view")]
    public viewType[] view {
        get {
            return this.viewField;
        }
        set {
            this.viewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class tagListType {
    
    private tagType[] tagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tag")]
    public tagType[] tag {
        get {
            return this.tagField;
        }
        set {
            this.tagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tableau.com/api")]
public partial class tableauCredentialsType {
    
    private siteType siteField;
    
    private userType userField;
    
    private string nameField;
    
    private string passwordField;
    
    private string tokenField;
    
    /// <remarks/>
    public siteType site {
        get {
            return this.siteField;
        }
        set {
            this.siteField = value;
        }
    }
    
    /// <remarks/>
    public userType user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string token {
        get {
            return this.tokenField;
        }
        set {
            this.tokenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tableau.com/api")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tableau.com/api", IsNullable=false)]
public partial class tsResponse {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("connection", typeof(connectionType))]
    [System.Xml.Serialization.XmlElementAttribute("connections", typeof(connectionListType))]
    [System.Xml.Serialization.XmlElementAttribute("credentials", typeof(tableauCredentialsType))]
    [System.Xml.Serialization.XmlElementAttribute("datasource", typeof(dataSourceType))]
    [System.Xml.Serialization.XmlElementAttribute("datasources", typeof(dataSourceListType))]
    [System.Xml.Serialization.XmlElementAttribute("error", typeof(errorType))]
    [System.Xml.Serialization.XmlElementAttribute("extracts", typeof(extractListType))]
    [System.Xml.Serialization.XmlElementAttribute("favorites", typeof(favoriteListType))]
    [System.Xml.Serialization.XmlElementAttribute("fileUpload", typeof(fileUploadType))]
    [System.Xml.Serialization.XmlElementAttribute("group", typeof(groupType))]
    [System.Xml.Serialization.XmlElementAttribute("groups", typeof(groupListType))]
    [System.Xml.Serialization.XmlElementAttribute("job", typeof(jobType))]
    [System.Xml.Serialization.XmlElementAttribute("pagination", typeof(paginationType))]
    [System.Xml.Serialization.XmlElementAttribute("permissions", typeof(permissionsType))]
    [System.Xml.Serialization.XmlElementAttribute("project", typeof(projectType))]
    [System.Xml.Serialization.XmlElementAttribute("projects", typeof(projectListType))]
    [System.Xml.Serialization.XmlElementAttribute("schedules", typeof(scheduleListType))]
    [System.Xml.Serialization.XmlElementAttribute("site", typeof(siteType))]
    [System.Xml.Serialization.XmlElementAttribute("sites", typeof(siteListType))]
    [System.Xml.Serialization.XmlElementAttribute("tags", typeof(tagListType))]
    [System.Xml.Serialization.XmlElementAttribute("user", typeof(userType))]
    [System.Xml.Serialization.XmlElementAttribute("users", typeof(userListType))]
    [System.Xml.Serialization.XmlElementAttribute("views", typeof(viewListType))]
    [System.Xml.Serialization.XmlElementAttribute("workbook", typeof(workbookType))]
    [System.Xml.Serialization.XmlElementAttribute("workbooks", typeof(workbookListType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
